<?php 
  require_once "verif1.php";

  require_once "head.html";

?>


<?php 
  require_once "verif1.php";

  require_once "head.html";
  
?>

<style>
  .texto{
   padding-top: 7%;
  } 
   body{
     background-color: darkcyan;
   }
   a{
     color: cyan;
   }
   p{
       width: 60%;
   }
   img{
       width: 60%;
       padding-bottom: 10px;
   }

</style>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>

  <div class=texto>
   <center>
   <h1>GÉNIE ECO-ENERGÉTIQUE ET ENVIRONNEMENT INDUSTRIEL :</h1>

       <p style="color: white;">LCette filière est spécialisée dans la formation des ingénieurs managers de l’énergie et de l’environnement, ouvert sur l’international ; capables de concevoir et de piloter des systèmes énergétiques ; de mettre en oeuvre une politique et conduire des projets de mise à niveau énergétiques et environnementaux au sein de l’entreprise.
</p>
     <img src="http://ensat.ac.ma/Portail/wp-content/uploads/2019/02/G3EI-S1.jpg" alt="" srcset="">
     <img src="http://ensat.ac.ma/Portail/wp-content/uploads/2019/02/G3EI-S2.jpg" alt="" srcset="">
     <img src="http://ensat.ac.ma/Portail/wp-content/uploads/2019/02/G3EI-S3.jpg" alt="" srcset="">
     <img src="http://ensat.ac.ma/Portail/wp-content/uploads/2019/02/G3EI-S4.jpg" alt="" srcset="">
     <img src="http://ensat.ac.ma/Portail/wp-content/uploads/2019/02/G3EI-S5.jpg" alt="" srcset="">


  </center>
</div>
</body>
</html>
