<?php 
  require_once "verif1.php";

  require_once "head.html";

?>


<?php 
  require_once "verif1.php";

  require_once "head.html";
  
?>

<style>
  .texto{
   padding-top: 7%;
  } 
   body{
     background-color: darkcyan;
   }
   a{
     color: cyan;
   }
   p{
       width: 60%;
   }
   img{
       width: 60%;
       padding-bottom: 10px;
   }

</style>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>

  <div class=texto>
   <center>
   <h1>GENIE INDUSTRIEL ET LOGISTIQUE :</h1>

       <p style="color: white;">cette filière vise à former des ingénieurs capables d’accompagner et de mener ses collaborateurs en industrie et en logistique vers les objectifs visés en mettant en oeuvre des qualités de relations humaines, de gestion d’équipe et de gestion de projet, pour expliquer, convaincre, motiver, animer, contrôler…
</p>
     <img src="http://ensat.ac.ma/Portail/wp-content/uploads/2019/02/GIL-S1.jpg" alt="" srcset="">
     <img src="http://ensat.ac.ma/Portail/wp-content/uploads/2019/02/GIL-S2.jpg" alt="" srcset="">
     <img src="http://ensat.ac.ma/Portail/wp-content/uploads/2019/02/GIL-S3.jpg" alt="" srcset="">
     <img src="http://ensat.ac.ma/Portail/wp-content/uploads/2019/02/GIL-S4.jpg" alt="" srcset="">
     <img src="http://ensat.ac.ma/Portail/wp-content/uploads/2019/02/GIL-S5.jpg" alt="" srcset="">


  </center>
</div>
</body>
</html>
