<?php 
  require_once "verif1.php";

  require_once "head.html";

?>


<?php 
  require_once "verif1.php";

  require_once "head.html";
  
?>

<style>
  .texto{
   padding-top: 7%;
  } 
   body{
     background-color: darkcyan;
   }
   a{
     color: cyan;
   }
   p{
       width: 60%;
   }
   img{
       width: 60%;
       padding-bottom: 10px;
   }

</style>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>

  <div class=texto>
   <center>
   <h1>GÉNIE DES SYSTÈMES ÉLECTRONIQUES ET AUTOMATIQUES :</h1>

       <p style="color: white;">Cette filière contribue à la formation d’ingénieur capable d’utiliser et de développer dans un premier temps ses connaissances techniques, de s’adapter rapidement aux situations particulières techniques, d’évoluer et de prendre de plus en plus de responsabilités.
</p>
     <img src="http://ensat.ac.ma/Portail/wp-content/uploads/2019/02/GSEA-S1.jpg" alt="" srcset="">
     <img src="http://ensat.ac.ma/Portail/wp-content/uploads/2019/02/GSEA-S2.jpg" alt="" srcset="">
     <img src="http://ensat.ac.ma/Portail/wp-content/uploads/2019/02/GSEA-S3.jpg" alt="" srcset="">
     <img src="http://ensat.ac.ma/Portail/wp-content/uploads/2019/02/GSEA-S4.jpg" alt="" srcset="">
     <img src="http://ensat.ac.ma/Portail/wp-content/uploads/2019/02/GSEA-S5.jpg" alt="" srcset="">
     <img src="http://ensat.ac.ma/Portail/wp-content/uploads/2019/02/GSEA-S5-.jpg" alt="" srcset="">


  </center>
</div>
</body>
</html>
