<?php 
  require_once "verif1.php";

  require_once "head.html";

?>


<?php 
  require_once "verif1.php";

  require_once "head.html";
  
?>

<style>
  .texto{
   padding-top: 7%;
  } 
   body{
     background-color: darkcyan;
   }
   a{
     color: cyan;
   }
   p{
       width: 60%;
   }
   img{
       width: 60%;
       padding-bottom: 10px;
   }

</style>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>

  <div class=texto>
   <center>
   <h1> GÉNIE DES SYSTÈMES DE TÉLÉCOMMUNICATION ET RÉSEAUX :</h1>

       <p style="color: white;">Cette filière à pour mission de former des ingénieurs avec des compétences dans la conception, le développement, l’exploitation et la gestion des systèmes de traitement et de transmission de l’information, l’administration de réseaux et de base de données.
</p>
     <img src="http://ensat.ac.ma/Portail/wp-content/uploads/2019/02/GSTR-S1.jpg" alt="" srcset="">
     <img src="http://ensat.ac.ma/Portail/wp-content/uploads/2019/02/GSTR-S2.jpg" alt="" srcset="">
     <img src="http://ensat.ac.ma/Portail/wp-content/uploads/2019/02/GSTR-S3.jpg" alt="" srcset="">
     <img src="http://ensat.ac.ma/Portail/wp-content/uploads/2019/02/GSTR-S4.jpg" alt="" srcset="">
     <img src="http://ensat.ac.ma/Portail/wp-content/uploads/2019/02/GSTR-S5.jpg" alt="" srcset="">
     <img src="http://ensat.ac.ma/Portail/wp-content/uploads/2019/02/GSTR-S5-.jpg" alt="" srcset="">


  </center>
</div>
</body>
</html>
